divert(-1)
define(loc,0)
define(word,``define($1,'eval(loc)`)'define(`loc', eval(loc + 1))')
define(label,``define($1,'eval(loc)`)'')
define(halt, `define(`loc', eval(loc + 1))dnl')
define(div, `define(`loc', eval(loc + 2))dnl')
define(mul, `define(`loc', eval(loc + 2))dnl')
define(sub, `define(`loc', eval(loc + 2))dnl')
define(add, `define(`loc', eval(loc + 2))dnl')
define(load, `define(`loc', eval(loc + 2))dnl')
define(store, `define(`loc', eval(loc + 2))dnl')
define(ba, `define(`loc', eval(loc + 2))dnl')
define(blt0, `define(`loc', eval(loc + 2))dnl')
define(ble0, `define(`loc', eval(loc + 2))dnl')
define(beq0, `define(`loc', eval(loc + 2))dnl')
define(bne0, `define(`loc', eval(loc + 2))dnl')
define(bge0, `define(`loc', eval(loc + 2))dnl')
define(bgt0, `define(`loc', eval(loc + 2))dnl')
define(print, `define(`loc', eval(loc + 2))dnl')
define(end,`dnl')
define(comment, `')
divert
